// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BtnLandingController from "./btn_landing_controller"
application.register("btn-landing", BtnLandingController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LandingPageController from "./landing_page_controller"
application.register("landing-page", LandingPageController)
