// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimeFormController from "./anime_form_controller"
application.register("anime-form", AnimeFormController)

import BtnLandingController from "./btn_landing_controller"
application.register("btn-landing", BtnLandingController)

import BtnReturnController from "./btn_return_controller"
application.register("btn-return", BtnReturnController)

import BtnReturnFromNewAnimeController from "./btn_return_from_new_anime_controller"
application.register("btn-return-from-new-anime", BtnReturnFromNewAnimeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HorizontalScrollController from "./horizontal_scroll_controller"
application.register("horizontal-scroll", HorizontalScrollController)

import IndexFadeInController from "./index_fade_in_controller"
application.register("index-fade-in", IndexFadeInController)

import IndexFadeOutController from "./index_fade_out_controller"
application.register("index-fade-out", IndexFadeOutController)

import LandingPageController from "./landing_page_controller"
application.register("landing-page", LandingPageController)

import ShowTransitionController from "./show_transition_controller"
application.register("show-transition", ShowTransitionController)
